#配置数据源
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#      url: jdbc:log4jdbc:sqlserver://192.168.10.15:1433;DatabaseName=taisu-hik
#      username: sa
#      password: tsdz@2021
      url: jdbc:log4jdbc:sqlserver://192.168.1.29:1433;DatabaseName=taisu-hik
      username: sa
      password: nbhy123456
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 10
      # 最大连接数
      max-active: 20
      # 获取连接超时时间
      max-wait: 5000
      # 连接有效性检测时间
      time-between-eviction-runs-millis: 60000
      # 连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      # 连接在池中最大生存的时间
      max-evictable-idle-time-millis: 900000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 检测连接是否有效
      validation-query: select 1
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true


# 登录相关配置
login:
  #  是否限制单用户登录
  single: false
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    heigth: 36
    # 内容长度
    length: 2

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: NBHY
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000



#是否开启 swagger-ui
swagger:
  enabled: true
# IP 本地解析

ip:
  local-parsing: false


logging:
  enable: true


# 文件存储路径
file:
  linux:
    path: /home/nbhy/file/
  windows:
    path: D:\nbhy\file\
  # 文件大小 /M
  maxSize: 100
  baseUrl: http://localhost:${server.port}/file/
  enabled: false

storage:
  type: localstorage
  #  type: localstorage
  #是否开启定时清理图片任务
  quartz: true



hik:
  host: 192.168.10.16:443
  appKey: 28597477
  appSecret: 1ugtioooqS6uJDYaBlH1
  ssl: true

erp:
  host: http://192.168.10.14/prod-api


